version: '2'
services:
  movie-project:
    container_name: movie-project-app
    image: lorisleiva/laravel-docker
    command: php /var/www/artisan serve --host=0.0.0.0 --port=4001
    ports:
      - 4001:4001
    volumes:
      - ./:/var/www/
    depends_on:
      - database
    environment:
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - movie-project-network

  database:
    container_name: movie-project-database
    image: mysql:8.0
    volumes:
      - "./data/mysql:/var/lib/mysql"
    command: [
        'mysqld',
        '--character-set-server=utf8',
        '--collation-server=utf8_general_ci'
    ]
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - movie-project-network

  adminer:
    container_name: movie-project-adminer
    image: adminer
    ports:
      - 8080:8080
    networks:
      - movie-project-network
    environment:
      ADMINER_DESIGN: lucas-sandery
    depends_on:
      - database

volumes:
  mysql_data:
networks:
  movie-project-network:
